data = [
    {"name": "Katy Perry", "follower_count": 94, "description": "musician", "country": "United States of America"},
    {"name": "Dwayne Johnson", "follower_count": 390, "description": "actor and entrepreneur", "country": "United States of America"},
    {"name": "Ariana Grande", "follower_count": 378, "description": "musician and actress", "country": "United States of America"},
    {"name": "Cristiano Ronaldo", "follower_count": 610, "description": "footballer", "country": "Portugal"},
    {"name": "Selena Gomez", "follower_count": 430, "description": "musician and actress", "country": "United States of America"},
    {"name": "Beyoncé", "follower_count": 320, "description": "musician", "country": "United States of America"},
    {"name": "Kim Kardashian", "follower_count": 365, "description": "TV personality and entrepreneur", "country": "United States of America"},
    {"name": "Justin Bieber", "follower_count": 289, "description": "musician", "country": "Canada"},
    {"name": "Lionel Messi", "follower_count": 470, "description": "footballer", "country": "Argentina"},
    {"name": "Shakira", "follower_count": 85, "description": "musician", "country": "Colombia"},
    {"name": "Taylor Swift", "follower_count": 270, "description": "musician", "country": "United States of America"},
    {"name": "Kylie Jenner", "follower_count": 400, "description": "TV personality and entrepreneur", "country": "United States of America"},
    {"name": "Zendaya", "follower_count": 200, "description": "actress", "country": "United States of America"},
    {"name": "Will Smith", "follower_count": 75, "description": "actor", "country": "United States of America"},
    {"name": "Billie Eilish", "follower_count": 115, "description": "musician", "country": "United States of America"},
    {"name": "Drake", "follower_count": 140, "description": "musician", "country": "Canada"},
    {"name": "LeBron James", "follower_count": 155, "description": "basketball player", "country": "United States of America"},
    {"name": "Jennifer Lopez", "follower_count": 245, "description": "musician and actress", "country": "United States of America"},
    {"name": "Tom Holland", "follower_count": 100, "description": "actor", "country": "United Kingdom"},
    {"name": "Priyanka Chopra", "follower_count": 90, "description": "actress", "country": "India"},
    {"name": "Chris Hemsworth", "follower_count": 110, "description": "actor", "country": "Australia"},
    {"name": "Rihanna", "follower_count": 150, "description": "musician and entrepreneur", "country": "Barbados"},
    {"name": "Cardi B", "follower_count": 150, "description": "musician", "country": "United States of America"},
    {"name": "Shawn Mendes", "follower_count": 70, "description": "musician", "country": "Canada"},
    {"name": "Kendall Jenner", "follower_count": 290, "description": "model", "country": "United States of America"},
    {"name": "Miley Cyrus", "follower_count": 200, "description": "musician and actress", "country": "United States of America"},
    {"name": "Chris Evans", "follower_count": 30, "description": "actor", "country": "United States of America"},
    {"name": "David Beckham", "follower_count": 80, "description": "former footballer", "country": "United Kingdom"},
    {"name": "Nicki Minaj", "follower_count": 220, "description": "musician", "country": "Trinidad and Tobago"},
    {"name": "Vin Diesel", "follower_count": 85, "description": "actor", "country": "United States of America"}
]
